ktor:
  application:
    modules:
      - com.hexhyperion.aklatan.ApplicationKt.module
  deployment:
    port: ${SERVER_PORT}
  development: ${DEVELOPMENT_MODE}

jwt:
  issuer: "com.hexhyperion"
  audience: "com.hexhyperion.aklatan"
  accessTokenTimeoutMinutes: 10
  refreshTokenLength: 32
  refreshTokenTimeoutDays: 14

auth:
  registrationTokenLength: 24
  registrationTokenTimeoutHours: 3
  passwordResetTokenLength: 24
  passwordResetTokenTimeoutHours: 1

books:
  reservationDurationDays: 7
  borrowDurationDays: 28
  notificationBeforeBorrowEndDays: 3
  feePerDayPln: 0.35

db:
  host: db
  port: ${POSTGRES_PORT}
  database: ${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  driver: "org.postgresql.Driver"