services:
  client:
    build:
      context: ./AklatanClient
    ports:
      - "${CLIENT_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - server

  server:
    build: ./AklatanServer
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./AklatanServer/db/aklatan.sql:/docker-entrypoint-initdb.d/aklatan.sql
    expose:
      - "${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aklatan" ]
      interval: 3s
      retries: 3

  cron:
    image: imega/supercronic
    env_file:
      - .env
    volumes:
      - ./AklatanServer/cron/crontab:/etc/crontab
    command: [ "./etc/crontab" ]
    environment:
      - TZ=Europe/Warsaw