services:
  server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/aklatan.sql:/docker-entrypoint-initdb.d/aklatan.sql
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aklatan" ]
      interval: 3s
      retries: 3

  cron:
    image: imega/supercronic
    env_file:
      - .env
    volumes:
      - ./cron/crontab:/etc/crontab
    command: [ "/etc/crontab" ]
    environment:
      - TZ=Europe/Warsaw